[tool.poetry]
name = "metrics"
version = "0.1.0"
description = "Metrics from various sources"
authors = ["Jorge Calavia <1184336+jcalavia@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PyDriller = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
