on:
  pull_request:
      types: [opened, synchronize, reopened]

name: Pull Request workflow

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:

    - name: SCM
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup environment
      uses: actions/setup-python@v2
      with:
        python-version:  [ '3.8', '3.9' ]

    - name: Tox Execution
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox poetry
        echo "project_version=$(poetry version -s)" >> $GITHUB_ENV
        tox

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectVersion="${{ env.project_version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
