name: Close Pull Request
on:
  pull_request:
    types: [ closed ]

jobs:
  release_code:
    # this job will only run if the PR has been merged to main branch and changes comes from fix or feature branches
    if: ${{ (github.event.pull_request.merged == true) && (github.base_ref == 'main') && (startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'feature/') ) }}
    runs-on: ubuntu-latest
    steps:

    - name: SCM
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Feature
      if: startsWith(github.head_ref, 'feature/')
      run: |
        echo "version_type='minor'" >> $GITHUB_ENV

    - name: Bug
      if: startsWith(github.head_ref, 'fix/')
      run: |
        echo "version_type='patch'" >> $GITHUB_ENV

    - name: Bump version type ${{ env.version_type }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions poetry
        poetry version ${{ env.version_type }}
        echo "project_version=$(poetry version -s)" >> $GITHUB_ENV
        tox

    - uses: EndBug/add-and-commit@v7
      with:
        message: Bump version to ${{ env.project_version }}
        default_author: github_actions
        branch: 'main'
        add: 'pyproject.toml'
        tag: '${{ env.project_version }}'

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectVersion="${{ env.project_version }}"
          -Dsonar.branch.name=${{ github.base_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
