name: Close Pull Request
on:
  pull_request:
    types: [ closed ]

jobs:
  release:
    # this job will only run if the PR has been merged to main branch
    if: ${{ (github.event.pull_request.merged == true) && (github.base_ref == 'main') }}
    runs-on: ubuntu-latest
    steps:

    - name: SCM
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Feature
      if: startsWith(github.head_ref, 'feature/')
      run: |
        echo "version_type='minor'" >> $GITHUB_ENV

    - name: Bug
      if: startsWith(github.head_ref, 'fix/')
      run: |
        echo "version_type='patch'" >> $GITHUB_ENV

    - name: Bump version type ${{ env.version_type }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry version ${{ env.version_type }}
        echo "project_version=$(poetry version -s)" >> $GITHUB_ENV

    - uses: EndBug/add-and-commit@v7
      with:
        message: Bump version to ${{ env.project_version }}
        default_author: github_actions
        add: '.'
        tag: '${{ env.version_type }}'
