name: Close Pull Request
on:
  pull_request:
    types: [ closed ]

jobs:
  release:
    # this job will only run if the PR has been merged to main branch
    if: ${{ (github.event.pull_request.merged == true) && (github.base_ref == 'main') }}
    runs-on: ubuntu-latest
    steps:

    - name: SCM
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Bump minor version
      if: startsWith(github.head_ref, 'feature/')
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry version minor

    - name: Bump patch version
      if: startsWith(github.head_ref, 'fix/')
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry version patch
