name: Close Pull Request
on:
  pull_request:
    types: [ closed ]

jobs:
  release:
    # this job will only run if the PR has been merged to main branch
    if: ${{ (github.event.pull_request.merged == true) && (github.base_ref == 'main') }}
    runs-on: ubuntu-latest
    steps:

    - name: Bump minor version
      if: startsWith('feature/', ${{ github.head_ref }})
      run: |
        echo feature merged in PR #${{ github.event.number }}

    - name: Bump patch version
      if: startsWith('fix/', ${{ github.head_ref }})
      run: |
        echo fix merged in PR #${{ github.event.number }}
